"""Mirror the public Research Agent Skills docs into the Kalaris Labs docs hub."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


PRODUCT = "research-agent-skills"
SKIP_TOP_LEVEL = {"docs.json", "llms.txt", "maintainers", "overrides"}
LINK_PATTERN = re.compile(r'(\]\(|\b(?:href|src)=")/(?!/)')


def prefix_navigation(value: object) -> object:
    """Prefix paths in the source navigation without changing its structure."""
    if isinstance(value, list):
        return [prefix_navigation(item) for item in value]
    if isinstance(value, dict):
        output = {}
        for key, item in value.items():
            if key in {"pages", "root"} and isinstance(item, str):
                output[key] = f"{PRODUCT}/{item.lstrip('/')}"
            elif key == "pages" and isinstance(item, list):
                output[key] = [
                    f"{PRODUCT}/{page.lstrip('/')}" if isinstance(page, str) else prefix_navigation(page)
                    for page in item
                ]
            elif key == "href" and isinstance(item, str) and item.startswith("/"):
                output[key] = f"/{PRODUCT}{item}"
            else:
                output[key] = prefix_navigation(item)
        return output
    return value


def sync(source: Path, hub: Path) -> None:
    source = source.resolve(strict=True)
    hub = hub.resolve(strict=True)
    destination = hub / PRODUCT
    if not (source / "docs.json").is_file():
        raise ValueError(f"Missing docs.json in {source}")
    if destination.resolve() != (hub / PRODUCT).resolve() or destination == source:
        raise ValueError("Unexpected destination")

    # This directory is wholly generated by this script; never remove hub pages.
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir()
    for item in source.iterdir():
        if item.name in SKIP_TOP_LEVEL:
            continue
        target = destination / item.name
        if item.is_dir():
            shutil.copytree(item, target)
        elif item.is_file():
            shutil.copy2(item, target)

    for page in destination.rglob("*"):
        if page.suffix not in {".md", ".mdx"} or not page.is_file():
            continue
        original = page.read_text(encoding="utf-8")
        updated = LINK_PATTERN.sub(rf"\1/{PRODUCT}/", original)
        if updated != original:
            page.write_text(updated, encoding="utf-8")

    source_config = json.loads((source / "docs.json").read_text(encoding="utf-8"))
    config_path = hub / "docs.json"
    hub_config = json.loads(config_path.read_text(encoding="utf-8"))
    products = hub_config["navigation"]["products"]
    product = next(item for item in products if item.get("product") == "Research Agent Skills")
    source_navigation = prefix_navigation(source_config["navigation"])
    for key in ("groups", "tabs", "pages", "anchors", "dropdowns"):
        product.pop(key, None)
    product.update(source_navigation)
    config_path.write_text(json.dumps(hub_config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="Source repository's docs directory")
    args = parser.parse_args()
    sync(args.source, Path(__file__).resolve().parents[1])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
